spring:
  datasource:
    url: jdbc:tc:postgresql:15://localhost/test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always