INSERT INTO USERS (ID,
                   USERNAME,
                   PASSWORD,
                   FULL_NAME,
                   EMAIL,
                   PROFESSIONAL_DOCUMENT,
                   ROLE,
                   SPECIALTY,
                   ACTIVE,
                   CREATED_AT,
                   UPDATED_AT)
VALUES ('e7ad215b-d7d2-4df3-873a-b5b292fcdcf3',
        'admin',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
        'Dr. Administrador Sistema',
        'admin@prontosus.com',
        'CRM123456',
        'ADMIN',
        'Clínico Geral',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('f8bd326c-e8e3-5ef4-974b-c6c393ged4f4',
        'dr.silva',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
        'Dr. João Silva',
        'joao.silva@prontosus.com',
        'CRM654321',
        'DOCTOR',
        'Cardiologia',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('a9ce437d-f9f4-6fg5-085c-d7d404hfe5g5',
        'enf.maria',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
        'Maria Santos',
        'maria.santos@prontosus.com',
        'COREN78901',
        'NURSE',
        'Enfermagem Geral',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);


INSERT INTO PATIENTS (ID,
                      CPF,
                      FULL_NAME,
                      BIRTH_DATE,
                      GENDER,
                      PHONE_NUMBER,
                      EMAIL,
                      ZIP_CODE,
                      STREET,
                      NUMBER,
                      COMPLEMENT,
                      NEIGHBORHOOD,
                      CITY,
                      STATE,
                      EMERGENCY_CONTACT_NAME,
                      EMERGENCY_CONTACT_PHONE,
                      KNOWN_ALLERGIES,
                      CURRENT_MEDICATIONS,
                      CHRONIC_CONDITIONS,
                      CREATED_AT,
                      UPDATED_AT)
VALUES ('p1a2b3c4-d5e6-7f8g-9h0i-j1k2l3m4n5o6',
        '12345678901',
        'Ana Costa Silva',
        '1985-03-15',
        'FEMALE',
        '11987654321',
        'ana.costa@email.com',
        '01310100',
        'Avenida Paulista',
        '1000',
        'Apto 101',
        'Bela Vista',
        'São Paulo',
        'SP',
        'José Silva',
        '11976543210',
        'Penicilina',
        'Losartana 50mg',
        'Hipertensão arterial',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('p2b3c4d5-e6f7-8g9h-0i1j-k2l3m4n5o6p7',
        '98765432100',
        'Carlos Eduardo Santos',
        '1975-07-22',
        'MALE',
        '11912345678',
        'carlos.santos@email.com',
        '04038001',
        'Rua Vergueiro',
        '2000',
        'Casa 2',
        'Vila Mariana',
        'São Paulo',
        'SP',
        'Ana Santos',
        '11923456789',
        'Aspirina',
        'Metformina 850mg',
        'Diabetes tipo 2',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('p3c4d5e6-f7g8-9h0i-1j2k-l3m4n5o6p7q8',
        '45678912300',
        'Mariana Oliveira',
        '1992-11-08',
        'FEMALE',
        '21987654321',
        'mariana.oliveira@email.com',
        '22070030',
        'Avenida Copacabana',
        '500',
        'Cobertura',
        'Copacabana',
        'Rio de Janeiro',
        'RJ',
        'Roberto Oliveira',
        '21976543210',
        'Nenhuma conhecida',
        'Vitamina D',
        'Nenhuma',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO APPOINTMENTS (ID,
                          PATIENT_ID,
                          HEALTHCARE_PROFESSIONAL_ID,
                          SCHEDULED_DATE_TIME,
                          STATUS,
                          TYPE,
                          REASON,
                          NOTES,
                          CREATED_AT,
                          UPDATED_AT)
VALUES ('a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6',
        'p1a2b3c4-d5e6-7f8g-9h0i-j1k2l3m4n5o6',
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4',
        '2024-01-15T10:30:00',
        'SCHEDULED',
        'CONSULTATION',
        'Dor de cabeça persistente',
        'Paciente relata cefaleia há 3 dias',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('a2c3d4e5-f6g7-8h9i-0j1k-l2m3n4o5p6q7',
        'p2b3c4d5-e6f7-8g9h-0i1j-k2l3m4n5o6p7',
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4',
        '2024-01-16T14:00:00',
        'SCHEDULED',
        'FOLLOW_UP',
        'Acompanhamento diabetes',
        'Consulta de rotina para controle glicêmico',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO MEDICAL_RECORDS (ID,
                             PATIENT_ID,
                             HEALTHCARE_PROFESSIONAL_ID,
                             APPOINTMENT_ID,
                             CONSULTATION_DATE,
                             CHIEF_COMPLAINT,
                             HISTORY_OF_PRESENT_ILLNESS,
                             PHYSICAL_EXAMINATION,
                             DIAGNOSIS,
                             TREATMENT,
                             PRESCRIPTIONS,
                             OBSERVATIONS,
                             SYSTOLIC_PRESSURE,
                             DIASTOLIC_PRESSURE,
                             HEART_RATE,
                             TEMPERATURE,
                             RESPIRATORY_RATE,
                             WEIGHT,
                             HEIGHT,
                             OXYGEN_SATURATION,
                             CREATED_AT,
                             UPDATED_AT)
VALUES ('mr1a2b3c-4d5e-6f7g-8h9i-0j1k2l3m4n5o',
        'p1a2b3c4-d5e6-7f8g-9h0i-j1k2l3m4n5o6',
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4',
        'a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6',
        '2024-01-05T10:30:00',
        'Dor de cabeça há 3 dias',
        'Paciente relata cefaleia de moderada intensidade, pulsátil, localizada na região temporal bilateral. Iniciou há 3 dias, sem fatores desencadeantes aparentes.',
        'Paciente em bom estado geral, hidratada, corada. PA: 140/90 mmHg. FC: 75 bpm. Exame neurológico sem alterações focais.',
        'Cefaleia tensional',
        'Orientações sobre higiene do sono, controle do estresse e medicação sintomática',
        'Dipirona 500mg - 1 comprimido a cada 6 horas se dor\nParacetamol 750mg - 1 comprimido a cada 8 horas\nRetorno em 7 dias se não houver melhora',
        'Paciente orientada sobre sinais de alerta para cefaleia secundária. Reforçada importância do controle da pressão arterial.',
        140,
        90,
        75,
        36.5,
        16,
        68.0,
        165.0,
        98.0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('mr2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
        'p2b3c4d5-e6f7-8g9h-0i1j-k2l3m4n5o6p7',
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4',
        'a2c3d4e5-f6g7-8h9i-0j1k-l2m3n4o5p6q7',
        '2024-01-05T14:00:00',
        'Consulta de rotina para acompanhamento do diabetes',
        'Paciente diabético tipo 2 diagnosticado há 5 anos, em uso de metformina. Refere adesão adequada ao tratamento e dieta. Glicemia capilar domiciliar entre 110-140 mg/dL.',
        'Paciente em bom estado geral. PA: 130/80 mmHg. Peso estável. Exame dos pés sem alterações. Ausculta cardiopulmonar normal.',
        'Diabetes mellitus tipo 2 com controle glicêmico adequado',
        'Manutenção do esquema terapêutico atual. Reforço das orientações dietéticas e atividade física regular.',
        'Metformina 850mg - 1 comprimido 2 vezes ao dia às refeições\nGlicemia capilar em jejum diariamente\nHemoglobina glicada a cada 3 meses',
        'Paciente bem orientado sobre autocuidado. Próxima consulta em 3 meses com resultados de exames laboratoriais.',
        130,
        80,
        70,
        36.2,
        14,
        82.0,
        175.0,
        99.0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);


INSERT INTO FILE_ATTACHMENTS (ID,
                              MEDICAL_RECORD_ID,
                              FILE_NAME,
                              FILE_PATH,
                              CONTENT_TYPE,
                              FILE_SIZE,
                              FILE_TYPE,
                              DESCRIPTION,
                              UPLOADED_AT,
                              UPLOADED_BY)
VALUES ('fa1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p',
        'mr1a2b3c-4d5e-6f7g-8h9i-0j1k2l3m4n5o',
        'exame_sangue_ana.pdf',
        'uploads/fa1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p.pdf',
        'application/pdf',
        245760,
        'EXAM_RESULT',
        'Hemograma completo e perfil lipídico',
        CURRENT_TIMESTAMP,
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4'),
       ('fa2c3d4e-5f6g-7h8i-9j0k-1l2m3n4o5p6q',
        'mr2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
        'glicemia_carlos.pdf',
        'uploads/fa2c3d4e-5f6g-7h8i-9j0k-1l2m3n4o5p6q.pdf',
        'application/pdf',
        189440,
        'EXAM_RESULT',
        'Curva glicêmica e hemoglobina glicada',
        CURRENT_TIMESTAMP,
        'f8bd326c-e8e3-5ef4-974b-c6c393ged4f4');